databases:
  - name: api_db
    databaseName: BackEndAPIContext
    user: postgres
    plan: free

services:
  - type: web
    name: backendapi
    env: docker
    plan: free
    autoDeploy: true
    region: oregon

    # Informa ao Render que o servi√ßo depende do banco
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://*:10000
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: api_db
          property: connectionString